name = "site-taskbot"
compatibility_date = "2023-10-14"

[site]
bucket = "./dist"

[build]
command = "npm run build"

# Añadir esta propiedad que Cloudflare está buscando
pages_build_output_dir = "dist"